default: &DEFAULT

  # augmentations
  crop_size: 64
  jc_jit_limit: 7

  #  optimizer parameters
  lr: !!float 0.004
  momentum: !!float 0.9
  lr_warmup_epochs: 0
  weight_decay: 0.
  lr_milestones: [60, 90]

  train_data_path: '/tmp/train*.h5'
  valid_data_path: '/tmp/valid*.h5'
  num_data_workers: 6
  num_channels: 5

  # spec-z
  specz_upper_lim: !!float 0.4
  num_classes: 180

  max_epochs: 100
  batch_size: 256
  valid_batch_size_per_gpu: 512

  log_to_screen: !!bool True
  log_to_tensorboard: !!bool True
  save_checkpoint: !!bool True

baseline:
  <<: *DEFAULT
